---
- name: Copy private key, inventory, config, and playbook to EC2 and run the playbook
  hosts: web  
  tasks:
    - name: Copy private key to EC2
      ansible.builtin.copy:
        src: ~/semi_final_project/AWS-LB-Terraform/my_key.pem
        dest: /home/ubuntu/.ssh/my_key.pem
        mode: '0600'
      become: yes

    - name: Install Ansible
      ansible.builtin.apt:
        name: ansible
        state: latest
      become: yes

    - name: Copy inventory.1 to EC2
      ansible.builtin.copy:
        src: ~/semi_final_project/AWS-LB-Terraform/inventory.1
        dest: /home/ubuntu/inventory.1
        mode: '0644'
        
    - name: Copy Ansible_priv.cfg to EC2
      ansible.builtin.copy:
        src: ~/semi_final_project/AWS-LB-Terraform/Ansible_priv.cfg
        dest: /home/ubuntu/Ansible_priv.cfg
        mode: '0644'

    - name: Copy private playbook.yaml to EC2
      ansible.builtin.copy:
        src: ~/semi_final_project/AWS-LB-Terraform/private_playbook.yaml
        dest: /home/ubuntu/private_playbook.yaml
        mode: '0644'

    - name: Run ansible-playbook with inventory.1
      ansible.builtin.shell: >
        ansible-playbook /home/ubuntu/private_playbook.yaml -i /home/ubuntu/inventory.1 --private-key=/home/ubuntu/.ssh/my_key.pem --ssh-extra-args="-F /home/ubuntu/Ansible_priv.cfg"
      args:
        chdir: /home/ubuntu/
      become: yes
